# Generated by Django 5.1.4 on 2025-02-07 16:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bem',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='O formato da tag RFID deve ser XX:XX:XX:XX (hexadecimal).', regex='^([0-9A-Fa-f]{2}):([0-9A-Fa-f]{2}):([0-9A-Fa-f]{2}):([0-9A-Fa-f]{2})$')])),
                ('nome', models.CharField(max_length=100)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objetos.categoria')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objetos.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('cnpj', models.CharField(max_length=18, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='O formato do CNPJ deve ser 00.000.000/0000-00', regex='([0-9]{2}).([0-9]{3}).([0-9]{3})/([0-9]{4})-([0-9]{2})')])),
                ('nome', models.CharField(max_length=100)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(auto_now_add=True)),
                ('bem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objetos.bem')),
                ('de_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_de', to='objetos.departamento')),
                ('para_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_para', to='objetos.departamento')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
