# Generated by Django 5.1.4 on 2025-02-12 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bem',
            name='marca',
            field=models.ForeignKey(default='Genérico', on_delete=django.db.models.deletion.CASCADE, to='objetos.fornecedor', verbose_name='Marca'),
            preserve_default=False,
        ),
    ]
