# Generated by Django 5.1.4 on 2025-02-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetos', '0002_bem_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('data_atualizacao', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='bem',
            name='data_proxima_revisao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bem',
            name='status_manutencao',
            field=models.CharField(choices=[('em_manutencao', 'Em Manutenção'), ('proximo_revisao', 'Próximo da Revisão'), ('ok', 'OK')], default='ok', max_length=20),
        ),
        migrations.AddField(
            model_name='bem',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
