# Generated by Django 5.1.4 on 2025-02-13 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetos', '0003_patrimonio_bem_data_proxima_revisao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendada', models.DateField()),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída')], default='agendada', max_length=20)),
                ('bem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='objetos.bem')),
            ],
        ),
    ]
